paragraphs = [`<p>At the behest of Joseph Cogswell, John Jacob Astor placed a codicil in his will to bequeath $400,000(equivalent of $11.8 million in 2019) for the creation of a public library. After Astor's death in 1848, the resulting board of trustees executed the will's conditions and constructed the Astor Library in 1854 in the East Village. The library created was a free reference library; its books were not permitted to circulate.</p>` +

    `<p>Former Governor of New York and presidential candidate Samuel J. Tilden believed that a library with citywide reach was required, and upon his death in 1886, he bequeathed the bulk of his fortune—about $2.4 million (equivalent of $68 million in 2019)—to 'establish and maintain a free library and reading room in the city of New York.' This money would sit untouched in a trust for several years, until John Bigelow, a New York attorney, and Andrew Haswell Green,both trustees of the Tilden fortune, came up with an idea to merge two of the city's largest libraries.</p>` +

    `<p>Both the Astor and Lenox libraries were struggling financially. Although New York City already had numerous libraries in the 19th century,almost all of them were privately funded and many charged admission or usage fees. Bigelow, the most prominent supporter of the plan to merge the libraries found support in Lewis Cass Ledyard, a member of the Tilden Board, as well as John Cadwalader, on the Astor board. Eventually, John Stewart Kennedy, president of the Lenox board came to support the plan as well. On May 23, 1895, Bigelow, Cadwalader, and George L. Rives agreed to create 'The New York Public Library, Astor, Lenox and Tilden Foundations' The plan was hailed as an example of private philanthropy for the public good.[13] On December 11, John Shaw Billings was named as the library's first director. The newly established library consolidated with the grass-roots New York Free Circulating Library in February 1901.</p>` +

    `<p>In March, Andrew Carnegie tentatively agreed to donate $5.2 million (equivalent of $160 million in 2019) to construct sixty-five branch libraries in the city, with the requirement that they be operated and maintained by the City of New York. The Brooklyn and Queens public library systems which predated the consolidation of New York City, eschewed the grants offered to them and did not join the NYPL system; they believed that they would not get treatment equal to the Manhattan and the Bronx counterparts. Later in 1901, Carnegie formally signed a contract with the City of New York to transfer his donation to the city in order to enable it to justify purchasing the land for building the branch libraries. The NYPL Board of trustees hired consultants for the planning, and accepted their recommendation that a limited number of architectural firms be hired to build the Carnegie libraries: this would ensure uniformity of appearance and minimize cost. The trustees hired McKim, Mead & White, Carrère and Hastings, and Walter Cook to design all the branch libraries.</p>`,

`<p>The consolidations and changes in collections have promoted continuing debate and controversy since 2004 when David Ferriero was named the Andrew W. Mellon Director and Chief Executive of the Research Libraries.NYPL had engaged consultants Booz Allen Hamilton to survey the institution, and Ferriero endorsed the survey's report as a big step " +"in the process of reinventing the library" The consolidation program has resulted in the elimination of subjects such as the Asian and Middle East Division (formerly named Oriental Division), as well as the Slavic and Baltic Division.</p>` +

`<p>A number of innovations in recent years have been criticized. In 2004 NYPL announced participation in the Google Books Library Project. By agreement between Google and major international libraries, selected collections of public domain books would be scanned in their entirety and made available online for free to the public. The negotiations between the two partners called for each to project guesses about ways that libraries are likely to expand in the future. According to the terms of the agreement, the data cannot be crawled or harvested by any other search engine; no downloading or redistribution is allowed. The partners and a wider community of research libraries can share the content.</p>` +

`<p>The sale of the separately endowed former Donnell Library in midtown provoked controversy.The elimination of Donnell was a result of the dissolution of children's, young adult and foreign language collections. The Donnell Media Center was also dismantled, the bulk of its collection relocated at the New York Public Library for the Performing Arts as the Reserve Film and Video Collection, with parts of its collection redistributed. The site was redeveloped for a luxury hotel.</p>`,

"<p>The New York Public Library was not created by government statute. From its earliest days, the library was formed from a partnership of city government with private philanthropy. As of 2010, the research libraries in the system are largely funded with private money, and the branch or circulating libraries are financed primarily with city government funds. Until 2009, the research and branch libraries operated almost entirely as separate systems, but that year various operations were merged. By early 2010, the NYPL staff had been reduced by about 16 percent, " +
"in part through the consolidations.</p>" +

"<p>In 2010, as part of the consolidation program, the NYPL moved various back-office operations to a new Library Services Center building in Long Island City. A former warehouse was renovated for this purpose for $50 million. In the basement, a new, $2.3 million book sorter uses bar codes on library items to sort them for delivery to 132 branch libraries. At two-thirds the length of a football field, the machine is the largest of its kind in the world, according to library officials. Books located in one branch and requested from another go through the sorter, which use has cut the previous waiting time by at least a day. Together with 14 library employees, the machine can sort 7,500 items an hour (or 125 a minute). On the first floor of the Library Services Center is an ordering and cataloging office; on the second, the digital imaging department (formerly at the Main Branch building) and the manuscripts and archives division, where the air is kept cooler; on the third, the Barbara Goldsmith Preservation Division, with a staff of 10 (as of 2010) but designed for as many as 30 employees.</p>" +

"<p>The NYPL maintains a force of NYC special patrolmen, who provide security and protection to various libraries, and NYPL special investigators, who oversee security operations at the library facilities. These officials have on-duty arrest authority granted by the New York Penal Law. Some library branches contract for security guards.To celebrate its 125th anniversary, the NYPL calculated a list of its most checked out books. Topping the list was Ezra Jack Keats' The Snowy Day, with The Cat in the Hat and Nineteen Eighty-Four rounding out the top three.</p>"
]

subtopics = ["Construction and Founding", "Controversies", "Recent History"]